# Generated by Django 5.1.4 on 2025-02-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('black_list', 'В чёрном списке')]},
        ),
    ]
