# Generated by Django 5.1.4 on 2024-12-26 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Семья',
                'verbose_name_plural': 'Семьи',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Род',
                'verbose_name_plural': 'Рода',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('tense_system', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('fut / non-fut', 'fut / non-fut'), ('pst / non-pst', 'pst / non-pst'), ('3 part', 'Трёхчастная'), ('no tenses', 'Нет времён')], max_length=15)),
                ('fut', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологический'), ('Anlt', 'Аналитический'), ('Both', 'Возможны оба'), ('---', 'Ни одного')], max_length=5)),
                ('pst', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологический'), ('Anlt', 'Аналитический'), ('Both', 'Возможны оба'), ('---', 'Ни одного')], max_length=5)),
                ('mm', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтверждённое да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('am', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтверждённое да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('ma', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтверждённое да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('aa', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтверждённое да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('main_comment', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.family')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.genus')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
    ]
