# Generated by Django 5.1.4 on 2025-01-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Семья',
                'verbose_name_plural': 'Семьи',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Род',
                'verbose_name_plural': 'Рода',
            },
        ),
        migrations.CreateModel(
            name='TheoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('outline', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Теоретический блок',
                'verbose_name_plural': 'Теоретический блок',
            },
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment_images/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.comment')),
            ],
            options={
                'verbose_name': 'Изображение комментария',
                'verbose_name_plural': 'Изображения комментариев',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('tense_system', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('fut / non-fut', 'fut / non-fut'), ('prs / non-prs', 'prs / non-prs'), ('pst / non-pst', 'pst / non-pst'), ('3 part', 'Трёхчастная'), ('no tenses', 'Нет времён')], max_length=15)),
                ('fut', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологич.'), ('Anlt', 'Аналитич.'), ('M + A', 'Возможны оба'), ('---', 'Ни одного')], max_length=5)),
                ('pst', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологич.'), ('Anlt', 'Аналитич.'), ('M + A', 'Возможны оба'), ('---', 'Ни одного')], max_length=5)),
                ('mm', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('am', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('ma', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('aa', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10)),
                ('main_comment', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.family')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.genus')),
                ('theory_blocks', models.ManyToManyField(related_name='languages', to='fut_in_pst_typology.theoryblock')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.language'),
        ),
    ]
