# Generated by Django 5.1.4 on 2025-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='progress',
            field=models.CharField(blank=True, choices=[(None, 'Не начат'), ('DN', 'Закончен'), ('CH', 'Проверить'), ('IP', 'Начат')], max_length=2),
        ),
    ]
