# Generated by Django 5.1.4 on 2025-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0002_language_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='progress',
            field=models.CharField(blank=True, choices=[(None, 'Не начат'), ('DN', 'Закончен'), ('CH', 'Проверить'), ('IP', 'Начат'), ('NI', 'Нет в Базе')], max_length=2),
        ),
    ]
