# Generated by Django 5.1.4 on 2024-12-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0002_comment_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='fut',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологический'), ('Anlt', 'Аналитический'), ('M + A', 'Возможны оба'), ('---', 'Ни одного')], max_length=5),
        ),
        migrations.AlterField(
            model_name='language',
            name='pst',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологический'), ('Anlt', 'Аналитический'), ('M + A', 'Возможны оба'), ('---', 'Ни одного')], max_length=5),
        ),
    ]
