# Generated by Django 5.1.4 on 2025-02-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0002_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Макро-ареал',
                'verbose_name_plural': 'Макро-ареалы',
            },
        ),
        migrations.AlterField(
            model_name='language',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.family'),
        ),
        migrations.AlterField(
            model_name='language',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.genus'),
        ),
        migrations.AlterField(
            model_name='language',
            name='theory_blocks',
            field=models.ManyToManyField(blank=True, related_name='languages', to='fut_in_pst_typology.theoryblock'),
        ),
        migrations.AddField(
            model_name='language',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fut_in_pst_typology.area'),
        ),
    ]
