# Generated by Django 5.1.4 on 2025-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0003_area_alter_language_family_alter_language_genus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='fut',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологич.'), ('Anlt', 'Аналитич.'), ('M + A', 'Возможны оба'), ('Clitic', 'Клитика'), ('---', 'Ни одного')], max_length=6),
        ),
        migrations.AlterField(
            model_name='language',
            name='pst',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологич.'), ('Anlt', 'Аналитич.'), ('M + A', 'Возможны оба'), ('Clitic', 'Клитика'), ('---', 'Ни одного')], max_length=6),
        ),
    ]
