# Generated by Django 5.1.4 on 2025-01-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0003_alter_language_fut_alter_language_pst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='aa',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='am',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='fut',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологич.'), ('Anlt', 'Аналитич.'), ('M + A', 'Возможны оба'), ('---', 'Ни одного')], max_length=5),
        ),
        migrations.AlterField(
            model_name='language',
            name='ma',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='mm',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('YES', 'Подтвержд. да'), ('not found', 'Кажется нет'), ('?', 'Непонятно'), ('---', 'Невозможно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='pst',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Mrph', 'Морфологич.'), ('Anlt', 'Аналитич.'), ('M + A', 'Возможны оба'), ('---', 'Ни одного')], max_length=5),
        ),
    ]
