# Generated by Django 5.1.4 on 2025-01-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0004_alter_language_aa_alter_language_am_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('outline', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('languages', models.ManyToManyField(related_name='theory_blocks', to='fut_in_pst_typology.language')),
            ],
            options={
                'verbose_name': 'Теоретический блок',
                'verbose_name_plural': 'Теоретический блок',
            },
        ),
    ]
