# Generated by Django 5.1.4 on 2025-04-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0005_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=400),
        ),
    ]
