# Generated by Django 5.1.4 on 2025-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0005_theoryblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theoryblock',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
