# Generated by Django 5.1.4 on 2025-01-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0006_alter_theoryblock_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theoryblock',
            name='languages',
        ),
        migrations.AddField(
            model_name='language',
            name='theory_blocks',
            field=models.ManyToManyField(related_name='languages', to='fut_in_pst_typology.theoryblock'),
        ),
    ]
