# Generated by Django 5.1.4 on 2025-01-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fut_in_pst_typology', '0007_remove_theoryblock_languages_language_theory_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='tense_system',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('fut / non-fut', 'fut / non-fut'), ('prs / non-prs', 'prs / non-prs'), ('pst / non-pst', 'pst / non-pst'), ('3 part', 'Трёхчастная'), ('no tenses', 'Нет времён')], max_length=15),
        ),
    ]
